<?php

function naked_requirements($phase) {
  $t = get_t();

  if (is_file(__DIR__.'/CSSNakedDay.js')) {
    return array(
      'CSSNakedDay.js' => array(
        'title' => 'CSSNakedDay.js',
        'severity' => REQUIREMENT_OK,
      ),
    );
  }

  return array(
    'naked' => array(
      'title' => 'CSSNakedDay.js',
      'severity' => REQUIREMENT_ERROR,
      'description' => $t(
        'You need to install the CSSNakedDay.js file from !url.',
        array('!url' => l('https://github.com/tobiassjosten/CSSNakedDay.js', 'https://github.com/tobiassjosten/CSSNakedDay.js'))
      ),
    ),
  );
}
